version: "3.8"

services:
  backend:
    image: ${DOCKERHUB_USERNAME}/seoul_server:latest
    container_name: deploy_container
    restart: always
    network_mode: host
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
